Repository ColinLefter/Accord, pull requests merged in 2024-03, with the labels that each got.

#73 Added 2 Design Patterns that will be implemented for your project.
  Reporting/M3 Document/Design Patterns.md
Labels: documentation, Task Size: M

#77 Added Sequence Diagrams for Friendlist Management and Notifications
  Reporting/Diagrams/M3/Team Accord_Sequence Diagram Friendlist Management and Notifications.pdf
Labels: documentation, Medium Priority

#78 added a sequence diagrams for server Owner and GroupChat owner
  Reporting/Diagrams/M3/Sequence Digram_groupChat_And_ServerOwner.pdf
Labels: documentation, Medium Priority

#75 Completed testing plan
  Reporting/testingPlan.md
Labels: documentation, High Priority

#76 Add Account Managing and Messaging sequence diagram
  Reporting/Diagrams/M3/Team Accord_Sequence diagram Acount Managing and Messaging.pdf
Labels: documentation

#82 Added Scrum meeting week 9 Report
  Reporting/ScrumMeetings/SCRUM-MEETING-Week 9.docx
Labels: documentation, High Priority

#86 Update Sequence Digram_groupChat_And_ServerOwner.pdf
  Reporting/Diagrams/M3/Sequence Digram_groupChat_And_ServerOwner.pdf
Labels: documentation

#87 M3 Report Finalized
  Reporting/Diagrams/M3/Sequence Digram_groupChat_And_ServerOwner.pdf
  Reporting/M2 Document/M2 Team Accord Report.pdf
  Reporting/M3 Document/COSC 310 - M3 - Team Accord.docx
  Reporting/M3 Document/COSC 310_M3_Team Accord.pdf
  Reporting/M3 Document/Design Patterns.md
  Reporting/testingPlan.md
Labels: documentation, High Priority, Task Size: M

#94 Messaging interface
  Application/Frontend/components/Messaging/Message.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/custom.css
  Application/Frontend/pages/accord.tsx
Labels: Feature

#103 Week 10 scrum report
  Reporting/ScrumMeetings/SCRUM-MEETING-Week 10.docx
Labels: documentation, Task Size: M

#108 Reverted messaging interface to working version
  Application/Frontend/__tests__/registrationOnSubmit.test.tsx
  Application/Frontend/__tests__/registrationOnSubmitExistedUsername.test.tsx
  Application/Frontend/__tests__/registrationOnSubmitPasswordMismatch.test.tsx
  Application/Frontend/components/Accounts/Registration.tsx
  Application/Frontend/components/tabstyling.module.css
  Application/Frontend/pages/accord.tsx
  Application/Frontend/pages/api/registration.tsx
  Application/Frontend/yarn.lock
Labels: enhancement

#102 User bar
  Application/Frontend/components/FriendProfile/friendsIcon.tsx
  Application/Frontend/components/LeftSidebar/ServerList.tsx
  Application/Frontend/components/userBar/UserInfo.tsx
  Application/Frontend/images/icons8-discord-48.png
  Application/Frontend/yarn.lock
  Application/package-lock.json
  Application/package.json
  package-lock.json
Labels: Feature

#100 Left sidebars (servers list)
  Application/Frontend/components/LeftSidebar/ServerList.tsx
  Application/Frontend/pages/_app.tsx
  Application/Frontend/pages/index.tsx
Labels: Feature

#110 Fixed issue with custom CSS not applying to all application components
  Application/Frontend/pages/_app.tsx
Labels: enhancement

#116 FriendsTab Component is now completed with database implementation.
  Application/Frontend/__tests__/FriendsTab.test.tsx
  Application/Frontend/components/FriendsColumn/FriendsTab.tsx
  Application/Frontend/pages/api/FriendsTab.tsx
Labels: enhancement, High Priority, Task Size: L, Feature, User story

#117 added query functionality for Search Box
  Application/Frontend/components/FriendsColumn/FriendsTab.tsx
Labels: enhancement, High Priority, Task Size: M, Feature

#119 Finalized Real-Time Direct Messaging
  Application/Frontend/__tests__/newMessage.test.tsx
  Application/Frontend/__tests__/privacy.test.tsx
  Application/Frontend/app/layout.tsx
  Application/Frontend/components/Messaging/Chat.tsx
  Application/Frontend/components/Messaging/Message.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/contexts/chatContext.tsx
  Application/Frontend/package-lock.json
  Application/Frontend/package.json
  Application/Frontend/pages/accord.tsx
  Application/Frontend/pages/api/ably-auth.tsx
  Application/Frontend/pages/api/get-message-history.tsx
  Application/Frontend/pages/api/update-message-history.tsx
  Application/Frontend/tsconfig.json
  Application/Frontend/yarn.lock
  package-lock.json
Labels: enhancement, High Priority, Task Size: XL, Feature

#125 Modified Registration.tsx and added registration.tsx before merge conflict happens
  Application/Frontend/components/Accounts/Registration.tsx
  Application/Frontend/pages/api/registration.tsx
Labels: enhancement

#127 User Profile Integration with Components + DB Integration
  Application/Frontend/components/FriendsColumn/FooterProfile.tsx
  Application/Frontend/components/UserSettings/UserSettings.tsx
  Application/Frontend/pages/api/userSettings.tsx
  Application/Frontend/pages/user-settings.tsx
Labels: Feature

#123 Implementing initialization of server list from database
  Application/Frontend/__tests__/getServersFromServerIDList.test.tsx
  Application/Frontend/__tests__/getServersOfLoggedInUser.test.tsx
  Application/Frontend/components/LeftSidebar/ServerList.tsx
  Application/Frontend/pages/api/getServersListOfUser.tsx
  Application/Frontend/pages/api/initializingServerList.tsx
  Application/Frontend/pages/left-sidebar.tsx
Labels: enhancement, Feature

#124 Implementing database to add servers in server list to database
  Application/Frontend/__tests__/addTab.test.tsx
  Application/Frontend/components/Accounts/Registration.tsx
  Application/Frontend/components/LeftSidebar/ServerList.tsx
  Application/Frontend/pages/api/servers.tsx
  Application/Frontend/pages/left-sidebar.tsx
Labels: enhancement, Feature

#137 User specific dms
  Application/Frontend/components/FriendsColumn/FriendsTab.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/pages/accord.tsx
Labels: Feature

#132 Added Summary portion of M4 report
  Reporting/M4 Document/Functionality Updates.md
  Reporting/M4 Document/Summary.md
  Reporting/M4 Document/Testing Strategy.md
Labels: documentation, High Priority, Task Size: M

#138 Friends/dm
  Application/Frontend/components/FriendProfile/FriendComponet.tsx
  Application/Frontend/components/FriendProfile/FriendList.tsx
  Application/Frontend/components/FriendsColumn/dmlist.tsx
Labels: Feature

#149 Critical Authentication Hot fixes (Urgent)
  Application/Frontend/components/FriendsColumn/FriendsTab.tsx
  Application/Frontend/middleware.ts
  Application/Frontend/package-lock.json
  Application/Frontend/package.json
  Application/Frontend/pages/api/FriendsTab.ts
  Application/Frontend/pages/api/ably-auth.ts
  Application/Frontend/pages/api/delete-user.ts
  Application/Frontend/pages/api/get-message-history.ts
  Application/Frontend/pages/api/getServersListOfUser.ts
  Application/Frontend/pages/api/initializingServerList.ts
  Application/Frontend/pages/api/login.ts
  Application/Frontend/pages/api/registration.ts
  Application/Frontend/pages/api/servers.ts
  Application/Frontend/pages/api/testMongoDB.ts
  Application/Frontend/pages/api/update-message-history.ts
  Application/Frontend/pages/api/update-user-data.ts
  Application/Frontend/pages/api/userSettings.ts
  Application/Frontend/pages/api/webhooks/clerk-mongodb-sync.ts
  Application/Frontend/pages/my-account.tsx
Labels: enhancement, High Priority, Task Size: M

#152 M4 Report finalized
  Reporting/M4 Document/M4_Team Accord.pdf
Labels: documentation, High Priority, Task Size: M

#146 Week 12 scrum report added
  Reporting/ScrumMeetings/SCRUM-MEETING-Week 12.docx
  Reporting/ScrumMeetings/~$RUM-MEETING-Week 12.docx
  Reporting/ScrumMeetings/~WRL0005.tmp
Labels: documentation

#157 Added UI Component for Member_List of a server
  Application/Frontend/components/Server/Member_List.tsx
  Application/Frontend/package-lock.json
  Application/Frontend/package.json
  Application/Frontend/pages/Member_List.tsx
Labels: High Priority, Task Size: M

#159 Patched non-functional chat history
  Application/Frontend/components/FriendsColumn/FooterProfile.tsx
  Application/Frontend/components/FriendsColumn/FriendsTab.tsx
  Application/Frontend/components/Messaging/Message.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/pages/accord.tsx
  Application/Frontend/pages/api/registration.ts
Labels: enhancement
