Repository ColinLefter/Accord, pull requests merged in 2024-04, with the labels that each got.

#182 Added scrum meeting report week 13
  Reporting/ScrumMeetings/SCRUM-MEETING-Week 13.docx
  Reporting/ScrumMeetings/SCRUM-MEETING-Week 13.pdf
Labels: documentation

#169 Delete message
  Application/Frontend/accordTypes.ts
  Application/Frontend/app/RootLayout.tsx
  Application/Frontend/components/Messaging/Chat.tsx
  Application/Frontend/components/Messaging/Message.tsx
  Application/Frontend/components/Messaging/MessageDropdown.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/contexts/chatContext.tsx
  Application/Frontend/pages/api/ably-auth.ts
  Application/Frontend/pages/api/delete-message.ts
Labels: enhancement, High Priority, Feature

#186 Friend notifcation improved
  Application/Frontend/components/FriendsColumn/AddFriendModal.tsx
  Application/Frontend/components/Navbar/notifcation.tsx
  Application/Frontend/package-lock.json
  Application/Frontend/package.json
  Application/Frontend/pages/accord.tsx
  Application/Frontend/pages/api/Get-Sent-Friend-Request.ts
  Application/Frontend/pages/api/Get-pending-Friend-Request.ts
  Application/Frontend/pages/api/accept-friend-request.ts
  Application/Frontend/pages/api/add-friend.ts
  Application/Frontend/pages/api/get-username-from-id.ts
  Application/Frontend/pages/notify.tsx
  package-lock.json
  package.json
Labels: enhancement, Feature

#187 Chat owner fix
  Application/Frontend/components/LeftSidebar/ServerList.tsx
  Application/Frontend/components/Messaging/MessageDropdown.tsx
  Application/Frontend/components/Messaging/MessagingInterface.tsx
  Application/Frontend/images/icons8-discord-48.png
  Application/Frontend/middleware.ts
  Application/Frontend/pages/accord.tsx
  Application/Frontend/pages/api/get-server-members.ts
  Application/Frontend/pages/server_appshell.tsx
  Application/Frontend/public/AccordLogo.svg
  Application/Frontend/public/AccordLogoLarge.png
Labels: enhancement, wontfix

#190 Intergrating member list to accord page
  Application/Frontend/components/Server/Member_List.tsx
  Application/Frontend/pages/accord.tsx
Labels: enhancement, Feature

#203 RealTimeSystemAdded for both send and recived friend request
  Application/components/Navbar/notifcation.tsx
  Application/package-lock.json
Labels: enhancement, Feature

#206 Completed Revised New Text Channel Modal to Facilitate the Transition from Group Chats to Text Channels
  Application/__tests__/BackToLanding.test.tsx
  Application/__tests__/LandingToLogin.test.tsx
  Application/__tests__/NewTextChannelBackendAPI.test.tsx
  Application/__tests__/NewTextChannelBackendAPICall.test.tsx
  Application/__tests__/accounts.test.tsx
  Application/__tests__/getServersFromServerIDList.test.tsx
  Application/accordTypes.ts
  Application/components/Messaging/MessagingInterface.tsx
  Application/components/Messaging/NewTextChannelModal.tsx
  Application/jest.config.cjs
  Application/package-lock.json
  Application/package.json
  Application/pages/accord.tsx
  Application/pages/api/new-text-channel.ts
  Application/pages/api/update-message-history.ts
  Application/utility.ts
Labels: enhancement, High Priority, Task Size: XL

#208 Implemented Text Channels in Left Sidebar, Refactored Application to Facilitate Transition to Text Channels
  Application/__tests__/NewTextChannelBackendAPI.test.tsx
  Application/accordTypes.ts
  Application/app/RootLayout.tsx
  Application/components/FriendsColumn/AddFriendModal.tsx
  Application/components/FriendsColumn/FooterProfile.tsx
  Application/components/FriendsColumn/FriendRequestManager.tsx
  Application/components/FriendsColumn/FriendsTab.tsx
  Application/components/FriendsColumn/Inbox.tsx
  Application/components/HeroBanner/HeroBanner.tsx
  Application/components/Messaging/Chat.tsx
  Application/components/Messaging/MessagingInterface.tsx
  Application/components/Messaging/NewTextChannelModal.tsx
  Application/components/TextChannels/TextChannelDemo.module.css
  Application/components/TextChannels/TextChannelDemo.tsx
  Application/components/TextChannels/TextChannelItem.module.css
  Application/components/TextChannels/TextChannelItem.tsx
  Application/components/TextChannels/TextChannels.tsx
  Application/contexts/activeViewContext.tsx
  Application/contexts/channelContext.tsx
  Application/contexts/chatContext.tsx
  Application/pages/accord.tsx
  Application/pages/api/add-friend.ts
  Application/pages/api/get-id-from-username.ts
  Application/pages/api/get-user-text-channels.ts
  Application/pages/api/new-chat.ts
  Application/pages/api/new-text-channel.ts
  Application/pages/index.tsx
  Application/utility.ts
  package-lock.json
  package.json
Labels: High Priority, Task Size: XL, Feature

#209 Completed Week 14 Scrum Report
  Reporting/ScrumMeetings/SCRUM MEETING WEEK 14.docx
  Reporting/ScrumMeetings/Week 14 Scrum Report.pdf
  Reporting/ScrumMeetings/~$RUM-MEETING-Week 14.docx
Labels: documentation, Task Size: S

#213 Fix rendering bugs of member list
  Application/components/Server/MemberList.tsx
  Application/components/TextChannels/TextChannels.tsx
  Application/pages/accord.tsx
Labels: bug, enhancement

#214 Fixed Privacy Toggle
  Application/accordTypes.ts
  Application/components/FriendsColumn/FriendsTab.tsx
  Application/components/Messaging/Chat.tsx
  Application/components/Messaging/MessageDropdown.tsx
  Application/components/Messaging/MessagingInterface.tsx
  Application/components/Messaging/NewTextChannelModal.tsx
  Application/components/Server/MemberList.tsx
  Application/components/TextChannels/TextChannelItem.tsx
  Application/components/TextChannels/TextChannels.tsx
  Application/pages/accord.tsx
  Application/pages/api/new-chat.ts
  Application/pages/api/removeMember.ts
  Application/utility.ts
Labels: enhancement, High Priority, Task Size: M

#216 Remove Friends from your user's Friendlist
  Application/components/FriendsColumn/RemoveFriendModal.tsx
  Application/pages/accord.tsx
  Application/pages/api/Remove-friend.ts
Labels: Feature

#218 Modal UI Adjustments
  Application/components/FriendsColumn/AddFriendModal.tsx
  Application/components/FriendsColumn/RemoveFriendModal.tsx
  Application/pages/accord.tsx
Labels: enhancement, Low Priority, Task Size: XS

#219 Patched critical message deletion malfunction
  Application/components/Messaging/MessageDropdown.tsx
Labels: enhancement, High Priority

#220 Real time channel fix
  Application/components/Messaging/MessagingInterface.tsx
  Application/components/Messaging/NewTextChannelModal.tsx
  Application/components/Server/MemberList.tsx
  Application/components/TextChannels/TextChannels.tsx
  Application/pages/api/new-chat.ts
  Application/pages/api/removeMember.ts
  Application/utility.ts
Labels: enhancement, High Priority

#222 Menu fix
  Application/accordTypes.ts
  Application/components/FriendsColumn/FriendsColumn.module.css
  Application/components/FriendsColumn/FriendsTab.tsx
  Application/components/Messaging/MessageDropdown.tsx
  Application/components/Server/MemberList.tsx
  Application/components/TextChannels/ChannelLoading.tsx
  Application/components/TextChannels/TextChannelItem.module.css
  Application/components/TextChannels/TextChannelItem.tsx
  Application/components/TextChannels/TextChannels.tsx
  Application/pages/accord.tsx
Labels: enhancement, High Priority

#224 Admin Promotion Implemented
  Application/components/Server/MemberList.tsx
  Application/pages/api/admin-promotion.ts
Labels: enhancement, Feature

#226 Bugfixing workflow .yml
  .github/workflows/node.js.yml
Labels: bug

#227 Workflow refactoring and testing
  .github/workflows/node.js.yml
Labels: bug

#228 Patched Non-Functional Tests | Added further tests for Accounts and Chats collections
  Application/__tests__/BackToLanding.test.tsx
  Application/__tests__/FriendsTab.test.tsx
  Application/__tests__/LandingToLogin.test.tsx
  Application/__tests__/LoginToRegistration.test.tsx
  Application/__tests__/NewTextChannelBackendAPI.test.tsx
  Application/__tests__/NewTextChannelBackendAPICall.test.tsx
  Application/__tests__/RegistrationToLogin.test.tsx
  Application/__tests__/RelinquishAdminAPI.test.tsx
  Application/__tests__/addTab.test.tsx
  Application/__tests__/getAccountByID.test.tsx
  Application/__tests__/getDMChannelByChannelKey.test.tsx
  Application/__tests__/getServersOfLoggedInUser.test.tsx
  Application/__tests__/getTextChannelByChannelKey.test.tsx
Labels: enhancement, High Priority, Task Size: M

#234 Removed Redundant Tests | Critical Hotfix
  Application/__tests__/LoginToRegistration.test.tsx
  Application/__tests__/RegistrationToLogin.test.tsx
Labels: High Priority

#235 Identified Issue on Automation Failing | Implemented Critical Hotfix
  Application/__tests__/NewTextChannelBackendAPI.test.tsx
  Application/__tests__/NewTextChannelBackendAPICall.test.tsx
  Application/__tests__/getAccountByID.test.tsx
  Application/__tests__/getDMChannelByChannelKey.test.tsx
  Application/__tests__/getTextChannelByChannelKey.test.tsx
Labels: High Priority

#236 [HOTFIX] Specified next.js version in package.json to address deployment issues
  Application/package-lock.json
  Application/package.json
Labels: High Priority
